# Generated by Django 4.2.2 on 2023-07-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0003_auto_20230630_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
